### ISSUE TITLE
Question about fetching myDB tables

### ISSUE THREAD

**Issue by MikeeRead** [dfm/casjobs#10]
Sorry more of a question than an issue (hi again Rick if you're reading this :) ).

When using the various functions casjobs (request_and_get_output) or mastcasjobs (fast_table) to retrieve myDBs tables is there any sorting applied. 

I'm running queries that sort my results into say myTable, but I suspect there is no guarantee that when they are retrieved that they necessarily come out in the same order, i.e. behind the scenes it's just a select * from myTable. SQL Server does not output in a particular order unless specified.

I'm pretty sure this is the case, but can't replicate it now!

Thanks
  MIke

**Comment by dfm** [comment]
cc @rlwastro?

I have no idea what the answer is!

**Comment by MikeeRead** [comment]
No worries. There doesn't seem a way via the web interface to specify a sorting on download so the possibility probably doesn't exist and it's safer to assume it could come back in a different order and sort the downloaded file and re-write it out. If there had been something exposed in the API (request_and_get_sortedOutput) I could save a step.

I'll be loading the files back in to a database and it's quicker if you can "tell" the insert command that the data are already sorted.
cheers
  Mike

**Comment by rlwastro** [comment]
Hi Mike -- I'm pretty certain there is no way in the Casjobs interface to request the results to be sorted.  But it is easy to do in in the sql query by adding an `ORDER BY` clause.  Is there some reason you are looking for another way to do this?

**Comment by MikeeRead** [comment]
Hi Rick

I am doing it in the query eg

select  100000 * into myTable0 from stackObjectThin order by objId
download table and find max(objID) then
select  100000 * into myTable1 from stackObjectThin where objId > maxObjID order by objId
repeat a lot !!

(a bit more to it than that as objId is not unique)

but when I download the myTables as CSV then I believe casjobs / SQL server can return it in whatever order it chooses. Initially to find the max(ObjID) in a batch I'd just looked at the last row of the downloaded CSV file but I don't think that is safe so I'm now reading in the whole download and saving the sorted version. In some early runs I'm pretty sure I got out of step with expected total number of rows retrieved vs actual retrieved because of this.

 I presume somewhere in casjobs there is the equivalent of

bcp out myTable.csv "select * from myTable"   (not the correct syntax!)

and wondered if maybe there was a way to add a where clause here. Still I gotta do some of the work! No worries though, I can do this locally and keep up with the queries.

Cheers
    Mike
Cheers
  Mike

**Comment by rlwastro** [comment]
We're hijacking Dan's casjobs discussion a bit -- but you might have a look at the [fast_table](https://github.com/rlwastro/mastcasjobs/blob/56dce599588f9db9be8b34e1e69c95b97e422aff/mastcasjobs.py#L181) method in [mastcasjobs](https://github.com/rlwastro/mastcasjobs).  It allows faster retrieval of MyDB tables.  The version of it in the mastcasjobs module converts the tab-separated text string to an astropy table.  It would be pretty easy to change it to get the raw tsv text output if that's what you want.  Or you can get the astropy.table version and write that as a csv file.  You can sort the table before writing it.

That's significantly faster than using the Casjobs output queue because you don't have to wait for the queue.  This only works with the MAST Casjobs server because it relies on a service completely outside Casjobs.

**Comment by MikeeRead** [comment]
I am running one extraction as a quick job using fast_table. I've also got another thread going using the queue.

Thanks both, sorry for the hijack! I'll close this.
